name: Feature Request
description: What kind of feature you suggest?
labels: ["new feature :new feature:"]
body:
- type: markdown
  attributes: 
    value: |
      ## Before you begin
      🚨 **INSTRUCTION, DO NOT SKIP**🚨
      
      Check for [issues](https://github.com/ShimizuTheLotus/Tagme_/issues) to make sure no one suggested this idea.

      **Plus, any features using internet will be declined directly. If you want that feature, create a folk repo yourself.**
      
- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: Describe the feature
     description: A clear and concise description of what the feature works

- type: textarea
  id: sketch
  attributes:
     label: Sketch
     description: If you have some pictures to show your idea, fell free to add them.
     
- type: textarea
  id: additional-context
  attributes:
     label: Additional context
     description: Add any other context about the problem here.
     
- type: dropdown
  id: contribution
  validations:
    required: true
  attributes:
     label: Have you already made it and waiting for merge?
     description: Have you have wrote code for the new feature?
     options:
       - Yes, It's all done and I'm waiting for merge.
       - Not yet, but I can finish it with someone help.
       - No, I just give my suggesstion.
